// <auto-generated />
namespace RestaurantApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Last1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Last1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005300858541_Last1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
